---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: harbor-secret-creator
spec:
  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")
    #@ load("@ytt:base64", "base64")
    #@ username = data.values.workload.metadata.namespace
    #@ auth = base64.encode("{}:Keepitsimple1".format(username))
    #@ dockerconfigjson = {"auths":{"harbor.tce-demo.samsanders.dev":{"username":username,"password":"Keepitsimple1","auth":auth}}}
    ---
    apiVersion: v1
    kind: Secret
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: harbor-credentials
    data:
      .dockerconfigjson: #@ base64.encode("{}".format(dockerconfigjson))