---
# this is for the postgres helm chart 
# it expects an "existing secret" that is used to configure the instance
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: postgres-secret-creator
spec:
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: postgres-creds
    data:
      postgres-password: YWRtaW4=
      password: a2VlcGl0c2ltcGxl