---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: postgres-helm-releaser
spec:
  template:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: postgresql-db
    spec:
      interval: 5m
      timeout: 5m
      chart:
        spec:
          chart: postgresql
          sourceRef:
            kind: HelmRepository
            name: bitnami
            namespace: helm-system
      values:
        auth:
          database: $(workload.metadata.name)$
          username: $(workload.metadata.name)$
          existingSecret: postgres-creds
        commonLabels:
          db: $(workload.metadata.name)$-postgresql
        global:
          storageClass: default
        primary:
          persistence:
            size: 8Gi
        shmVolume:
          enabled: false