---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: service-account-creator
spec:
  template:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: service-account
    secrets:
    - name: harbor-credentials
    - name: $(params.git_secret)$
    imagePullSecrets:
    - name: harbor-credentials