---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: source-to-url-with-postgres
spec:
  selector:
    apps.tanzu.vmware.com/workload-type: web-with-postgres
  serviceAccountRef:
    name: cartographer-catalog-default-sa
    namespace: default
  params:
    - name: registry
      default:
        repository: cartographer/supply-chain
        server: harbor.tce-demo.samsanders.dev
    - name: cluster_builder
      default: default
    - name: service_account
      default: service-account
    - name: git_implementation
      default: go-git
    - name: git_secret
      default: git-credentials
  resources:
    - name: harbor-secret-creator
      templateRef:
        kind: ClusterTemplate
        name: harbor-secret-creator
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: git-repository
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - resource: source-provider
          name: source
    - name: postgres-secret-creator
      templateRef:
        kind: ClusterTemplate
        name: postgres-secret-creator
    - name: postgres-app-config
      templateRef:
        kind: ClusterTemplate
        name: postgres-app-config
    - name: postgres-helm-releaser
      templateRef:
        kind: ClusterTemplate
        name: postgres-helm-releaser
    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-with-postgres-config
      images:
        - resource: image-builder
          name: image
