apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-role-binding
  namespace: dev-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-account-role
subjects:
- kind: ServiceAccount
  name: service-account
  namespace: dev-team
