apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: dev-team
secrets:
- name: harbor-credentials # supply chain will create this
- name: git-credentials
imagePullSecrets:
- name: harbor-credentials