apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: websocket-demo
  namespace: sample
spec:
  tag: harbor.tce-demo.samsanders.dev/demo-apps/websocket-demo
  serviceAccountName: harbor-service-account
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/p-ssanders/websocket-demo
      revision: 9ffd1f19678fca95a0fe1503664ae043592b872d
  build:
    env:
    - name: BP_JVM_VERSION
      value: "18"