---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: service-creator
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: $(workload.metadata.name)$
      name: $(workload.metadata.name)$-service
    spec:
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: $(workload.metadata.name)$