---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: app-deployer
spec:
  params:
    - name: harbor-service-account
      default: service-account
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: $(workload.metadata.name)$-deployment
      labels:
        app: $(workload.metadata.name)$
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: $(workload.metadata.name)$
      template:
        metadata:
          labels:
            app: $(workload.metadata.name)$
        spec:
          serviceAccountName: $(params.harbor-service-account)$
          containers:
            - name: $(workload.metadata.name)$
              image: $(images.built-image.image)$
              volumeMounts:
                - name: app-secrets
                  mountPath: /workspace/config/secrets
          volumes:
            - name: app-secrets
              secret:
                secretName: app-secrets