---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    workload-type: source-code
  resources:
    - name: retrieve-source
      templateRef:
        kind: ClusterSourceTemplate
        name: source-retriever
    - name: build-image
      templateRef:
        kind: ClusterImageTemplate
        name: image-builder
      sources:
        - name: retrieved-source
          resource: retrieve-source
    - name: deployment
      templateRef:
        kind: ClusterTemplate
        name: app-deployer
      images:
        - name: built-image
          resource: build-image
    - name: service
      templateRef:
        kind: ClusterTemplate
        name: app-service-creator
    - name: ingress
      templateRef:
        kind: ClusterTemplate
        name: app-ingress-creator
  serviceAccountRef:
    name: cartographer-sa
    namespace: cartographer-system
