---
apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: image-builder
spec:
  imagePath: .status.latestImage
  params:
    - name: harbor-project
      default: demo-apps
    - name: harbor-service-account
      default: service-account
  template:
    apiVersion: kpack.io/v1alpha2
    kind: Image
    metadata:
      name: $(workload.metadata.name)$
      labels:
        build: $(workload.metadata.name)$
    spec:
      tag: harbor.tce-demo.samsanders.dev/$(params.harbor-project)$/$(workload.metadata.name)$
      serviceAccountName: $(params.harbor-service-account)$
      builder:
        name: default
        kind: ClusterBuilder
      source:
        blob:
          url: $(sources.retrieved-source.url)$
      build:
        env:
        - name: BP_JVM_VERSION
          value: "18"