---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: knative-deployer
spec:
  params:
    - name: harbor-service-account
      default: service-account
  template:
    apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      name: $(workload.metadata.name)$
    spec:
      template:
        metadata:
          name: $(workload.metadata.name)$
          labels:
            app: $(workload.metadata.name)$
        spec:
          serviceAccountName: $(params.harbor-service-account)$
          containers:
            - name: $(workload.metadata.name)$
              image: $(images.built-image.image)$
              volumeMounts:
                - name: app-secrets
                  mountPath: /workspace/config/secrets
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: cloud
                - name: DEBUG
                  value: "true"
          volumes:
            - name: app-secrets
              secret:
                secretName: app-secrets
