---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: java-spring-from-source
spec:
  selector:
    workload-type: java-spring-source-code
  resources:
    - name: retrieve-source
      templateRef:
        kind: ClusterSourceTemplate
        name: source-retriever
    - name: build-image
      templateRef:
        kind: ClusterImageTemplate
        name: image-builder
      sources:
        - name: retrieved-source
          resource: retrieve-source
    - name: deployment
      templateRef:
        kind: ClusterTemplate
        name: knative-deployer
      images:
        - name: built-image
          resource: build-image
  serviceAccountRef:
    name: cartographer-sa
    namespace: cartographer-system
