# kubectl create secret docker-registry harbor-creds --docker-username=tce-demo-user --docker-password=${DOCKER_PASSWORD} --docker-server=harbor.tce-demo.samsanders.dev -n websocket-demo --dry-run=client -o yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: harbor-creds
  namespace: websocket-demo
data:
  .dockerconfigjson: DOCKER_CONFIG_JSON
