---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: websocket-demo
  namespace: websocket-demo
  labels:
    workload-type: source-code
spec:
  params:
    - name: harbor-project
      value: demo-apps
    - name: git-secret
      value: gitlab-creds
  source:
    git:
      url: ssh://git@github.com:22/p-ssanders/websocket-demo.git
      ref:
        branch: main