namespace: harbor
hostname: harbor.tce-demo.samsanders.dev
port:
  https: 443
logLevel: info
tlsCertificate:
  tls.crt:
  tls.key:
  ca.crt:
tlsCertificateSecretName: harbor-cert
enableContourHttpProxy: false
contourHttpProxy:
  timeout: 0s
  idleTimeout: 5m
harborAdminPassword: YOUR-PASSWORD
secretKey: YOUR-PASSWORD
database:
  password: YOUR-PASSWORD
  shmSizeLimit:
  maxIdleConns:
  maxOpenConns:
exporter:
  cacheDuration:
core:
  replicas: 1
  secret: YOUR-PASSWORD
  xsrfKey: YOUR-PASSWORD
jobservice:
  replicas: 1
  secret: YOUR-PASSWORD
registry:
  replicas: 1
  secret: YOUR-PASSWORD
notary:
  enabled: true
trivy:
  enabled: true
  replicas: 1
  gitHubToken: ""
  skipUpdate: false
persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 10Gi
    jobservice:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
  imageChartStorage:
    disableredirect: false
    type: filesystem
    filesystem:
      rootdirectory: /storage
    s3:
      region: us-west-2
      bucket: harbor
      accesskey: ACCESS_KEY
      secretkey: SECRET_KEY
      regionendpoint: null
      encrypt: false
      keyid: null
      secure: true
      skipverify: false
      v4auth: true
      chunksize: null
      rootdirectory: null
      storageclass: STANDARD
      multipartcopychunksize: null
      multipartcopymaxconcurrency: null
      multipartcopythresholdsize: null
proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal
pspNames: null
metrics:
  enabled: false
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  jobservice:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001
network:
  ipFamilies:
    - IPv4
    - IPv6
