# kubectl run postgresql-client --rm --tty -i --restart='Never' --namespace postgres-demo --image bitnami/postgresql:latest --env="PGPASSWORD=keepitsimple" --command -- psql --host postgresql-db-0 -U postgres-demo -d postgres-demo -p 5432
---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: postgresql-helm-releaser
spec:
  params:
    - name: postgresql-secret
      default: postgresql-creds
  template:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: postgresql-db
    spec:
      interval: 5m
      timeout: 5m
      chart:
        spec:
          chart: postgresql
          sourceRef:
            kind: HelmRepository
            name: bitnami
            namespace: helm-system
      values:
        auth:
          database: $(workload.metadata.namespace)$
          username: $(workload.metadata.namespace)$
          existingSecret: $(params.postgresql-secret)$
        commonLabels:
          db: $(workload.metadata.namespace)$-postgresql
        primary:
          persistence:
            storageClass: default
            size: 2Gi