---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: postgresql-helm-releaser
spec:
  params:
    - name: postgresql-secret
      default: postgresql-creds
  template:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: postgresql-db
    spec:
      interval: 10m
      timeout: 5m
      chart:
        spec:
          chart: postgresql
          sourceRef:
            kind: HelmRepository
            name: bitnami
            namespace: helm-system
      values:
        auth:
          database: $(workload.metadata.name)$
          username: $(workload.metadata.name)$
          existingSecret: $(params.postgresql-secret)$
        commonLabels:
          db: $(workload.metadata.name)$-postgresql
        primary:
          persistence:
            storageClass: default
            size: 2Gi