---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: postgresql-db
spec:
  selector:
    workload-type: postgresql-db
  resources:
    - name: helm-release
      templateRef:
        kind: ClusterTemplate
        name: postgresql-helm-releaser
  serviceAccountRef:
    name: cartographer-sa
    namespace: cartographer-system
