---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-release-role
rules:
  - apiGroups:
    - helm.toolkit.fluxcd.io
    resources:
    - helmreleases
    verbs:
    - list
    - create
    - update
    - delete
    - patch
    - watch
    - get