---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kservice-role
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get