---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: services-role
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get