---
# template for creating a deployment from an image
# kpack will build and publish an image upon commit (see websocket-demo/image.yaml)
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: app-deployment
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: $(workload.metadata.name)$-deployment
      labels:
        app: $(workload.metadata.name)$
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: $(workload.metadata.name)$
      template:
        metadata:
          labels:
            app: $(workload.metadata.name)$
        spec:
          containers:
            - name: $(workload.metadata.name)$
              image: $(workload.spec.image)$
          imagePullSecrets:
            - name: harbor-creds