---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cartographer-deployment-role-binding
  namespace: cartographer-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployments-role
subjects:
  - kind: ServiceAccount
    name: cartographer-sa
    namespace: cartographer-system