---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    workload-type: source-code
  resources:
    - name: build-image
      templateRef:
        kind: ClusterImageTemplate
        name: image-builder
    - name: deployment
      templateRef:
        kind: ClusterTemplate
        name: app-deployer
      images:
        - resource: build-image
          name: built-image
  serviceAccountRef:
    name: cartographer-sa
    namespace: cartographer-system
