apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-staging
spec:
  acme:
    email: hello@samsanders.dev
    privateKeySecretRef:
      name: aws-creds
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-west-2
          accessKeyID: AKIAZDKJFDI4CRCO2R7R
          secretAccessKeySecretRef:
            name: external-dns-iam-credentials
            key: secret-access-key